export const projects = [
  {
    id: 1,
    img: "/images/1.webp",
    title: "MIT Abstraction",
    date: "April 19, 2021",
  },
  {
    id: 2,
    img: "/images/2.webp",
    title: "MIT Site Plan",
    date: "April 19, 2021",
  },
  {
    id: 3,
    img: "/images/3.webp",
    title: "MIT Dusk",
    date: "April 19, 2021",
  },
  {
    id: 4,
    img: "/images/4.webp",
    title: "MIT Fall",
    date: "April 19, 2021",
  },
  {
    id: 5,
    img: "/images/5.webp",
    title: "MIT Pedestrian Street",
    date: "April 19, 2021",
  },
  {
    id: 6,
    img: "/images/6.webp",
    title: "MIT Winter Plaza",
    date: "April 19, 2021",
  },
  {
    id: 7,
    img: "/images/7.webp",
    title: "MIT Concept Diagram",
    date: "April 19, 2021",
  },
  {
    id: 8,
    img: "/images/8.webp",
    title: "Texas Aerial",
    date: "April 19, 2021",
  },
  {
    id: 9,
    img: "/images/9.webp",
    title: "Texas Bridges",
    date: "April 19, 2021",
  },
  {
    id: 10,
    img: "/images/10.webp",
    title: "Texas Abstraction",
    date: "April 19, 2021",
  },
  {
    id: 11,
    img: "/images/11.webp",
    title: "Texas Office Dusk",
    date: "June 29, 2020",
  },
  {
    id: 12,
    img: "/images/12.webp",
    title: "Texas Plairie Aerial",
    date: "June 29, 2020",
  },
  {
    id: 13,
    img: "/images/13.webp",
    title: "Texas Office Elevation",
    date: "June 29, 2020",
  },
  {
    id: 14,
    img: "/images/14.webp",
    title: "Porter Square Interior",
    date: "June 29, 2020",
  },
  {
    id: 15,
    img: "/images/15.webp",
    title: "Porter Square Platform",
    date: "June 29, 2020",
  },
  {
    id: 16,
    img: "/images/16.webp",
    title: "Porter Square Distant View",
    date: "June 29, 2020",
  },
  {
    id: 17,
    img: "/images/17.webp",
    title: "Porter Square Axon",
    date: "June 29, 2020",
  },
  {
    id: 18,
    img: "/images/18.webp",
    title: "Porter Square Winter",
    date: "June 29, 2020",
  },
  {
    id: 19,
    img: "/images/19.webp",
    title: "Porter Square Section",
    date: "June 29, 2020",
  },
  {
    id: 20,
    img: "/images/20.webp",
    title: "Porter Square Black & White",
    date: "June 29, 2020",
  },
];
