export const projects = [
  {
    id: 1,
    img: "/images/1.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 2,
    img: "/images/2.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 3,
    img: "/images/3.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 4,
    img: "/images/4.webp",
    title: "Laneway House Toronto",
    date: "2024",
  },
  {
    id: 5,
    img: "/images/5.webp",
    title: "Laneway House Toronto",
    date: "2024",
  },
  {
    id: 6,
    img: "/images/6.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 7,
    img: "/images/7.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 8,
    img: "/images/8.webp",
    title: "Cottage Muskoka",
    date: "2023",
  },
  {
    id: 9,
    img: "/images/9.webp",
    title: "Condominium Hamilton",
    date: "2022",
  },
  {
    id: 10,
    img: "/images/10.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 11,
    img: "/images/11.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 12,
    img: "/images/12.webp",
    title: "Residential Mississauga",
    date: "2023",
  },
  {
    id: 13,
    img: "/images/13.webp",
    title: "Residential Oakville",
    date: "2023",
  },
  {
    id: 14,
    img: "/images/14.webp",
    title: "Residential Oakville",
    date: "2023",
  },
  {
    id: 15,
    img: "/images/15.webp",
    title: "Residential Montreal",
    date: "2022",
  },
  {
    id: 16,
    img: "/images/16.webp",
    title: "Townhouses Mississauga",
    date: "2022",
  },
  {
    id: 17,
    img: "/images/17.webp",
    title: "Condominium Oakville",
    date: "2022",
  },
  {
    id: 18,
    img: "/images/18.webp",
    title: "Residential Montreal",
    date: "2022",
  },
  {
    id: 19,
    img: "/images/19.webp",
    title: "Commercial Toronto",
    date: "2022",
  },
  {
    id: 20,
    img: "/images/20.webp",
    title: "Condominium Oakville",
    date: "2022",
  },
  {
    id: 21,
    img: "/images/21.jpg",
    title: "Condominium Oakville",
    date: "2022",
  },
];
